pinkLightProject/accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
    path('login/', views.login, name="login"),
]

pinkLightProject/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('websockets/', include('websockets.urls')),
    path('webserver/', include('webserver.urls')),
    path('admin/', admin.site.urls),
]

pinkLightProject/webserver/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'webserver'
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.new, name="new"),
    path('<int:train_pk>/', views.detail, name="detail"),
    path('<str:train_no>/train_detail', views.train_detail, name="train_detail"),
    path('<int:train_pk>/edit/', views.edit, name="edit"),
    path('<int:train_pk>/delete/', views.delete, name="delete"),
    path('<int:notification_pk>', views.delete_notification, name="delete_notification"),
    path('<str:train_name>/station_info/', views.station_info, name="station_info"),
    path('<str:station>/station_status', views.station_status, name="station_status"),
    path('<str:seat_info>/pink_light', views.pink_light, name="pink_light"),
]

pinkLightProject/webserver/models.py
from django.db import models

# Create your models here.
class Train(models.Model):
    train_no = models.CharField(max_length=10)
    slot_no = models.CharField(max_length=10)
    seat_no = models.CharField(max_length=10)
    empty = models.BooleanField()

    def __str__(self):
        return f'[{self.train_no}] {self.slot_no} 번칸 {self.seat_no} : 사용여부: {self.empty}'


class Notification(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    # train = models.ForeignKey(Train, on_delete=models.CASCADE)

    def __str__(self):
        return f'[{self.pk}알림] {self.content} : {self.created_at}에 생성'

pinkLightProject/webserver/forms.py
from django import forms
from .models import Train

class TrainForm(forms.ModelForm):
    train_no = forms.CharField(max_length=10)
    slot_no = forms.CharField(max_length=10)
    seat_no = forms.CharField(max_length=10)

    class Meta:
        model = Train
        fields = ['train_no', 'slot_no', 'seat_no', ]

pinkLightProject/webserver/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Train, Notification
from django import forms
from .forms import TrainForm
from django.http import JsonResponse
from django.db.models import Count
import requests
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Count
from decouple import config

# Create your views here.
# @csrf_exempt
def pp(request, seat_info):
    if request.method == "POST":
        print('난 포스트')
    else:
        print('난 갯')

    context = {
        'aa' : seat_info,
    }
    return JsonResponse(context)


# @csrf_exempt
def pink_light(request, seat_info):
    train_no = seat_info[:6]
    slot_no = seat_info[6:9]
    seat_no = seat_info[9:]

    # 임산부석 상태 변경
    train = Train.objects.get(train_no=train_no, slot_no=slot_no, seat_no=seat_no)
    if train.empty :
        train.empty = False
    else :
        train.empty = True
    train.save()

    # 열차 정보 & 알림 가져오기
    status = ""
    if train.empty:
        status = "이용 완료"
    else : 
        status = "이용 중"
    content = f'{ train.train_no } 번 열차 {train.slot_no} 번째 칸 {train.seat_no} 번 임산부석 {status}'
    print(content)

    notify = Notification.objects.create(content=content)

    return redirect('webserver:index')

    # trains = Train.objects.all()

    # notifications = Notification.objects.all()
    
    # context = {
    #     'pink_light' : train,
    #     'trains' : trains,
    #     'notifications': notifications,
    # }
    # return render(request,'webserver/index.html', context)


# @csrf_exempt 
def station_status(request, station):
    print('뿜뿜뿜')

    if request.method == "POST":
        print('난 포스트')
    else:
        print('난 갯')

    print(station)
    api_url = 'http://swopenapi.seoul.go.kr/api/subway'
    key = config('SUBWAY_REAL_TIME')
    station_status = requests.get(f'{api_url}/{key}/json/realtimeStationArrival/0/5/{station}').json()
    print(station_status)
    data = station_status['realtimeArrivalList']
    print(len(data))
    t_no = data[0].get('btrainNo')
    t_no = "00" + t_no
    print(t_no)


    btrainNo = []
    trainLineNm = []
    arvlMsg2 = []
    empty_seat = []

    for i in range(len(data)):
        btrainNo.append(data[i].get('btrainNo'))
        trainLineNm.append(data[i].get('trainLineNm'))
        arvlMsg2.append(data[i].get('arvlMsg2'))
        empty_seat.append(i+1)

    context = {
        'btrainNo' : btrainNo,
        'trainLineNm' : trainLineNm,
        'arvlMsg2' : arvlMsg2,
        'empty_seat' : empty_seat,
    }
    return JsonResponse(context)


def station_info(request, train_name):
    print(train_name)
    context = {
        '상행' : [
            {
                '001002': [{
                    'slot_no' : '004',
                    'seat_no' : '01',
                    'empty' : False
                }, {
                    'slot_no' : '004',
                    'seat_no' : '02',                    
                    'empty' : False
                }, {
                    'slot_no' : '004',
                    'seat_no' : '03',                    
                    'empty' : False
                }, {
                    'slot_no' : '005',
                    'seat_no' : '01',                    
                    'empty' : False
                }, {
                    'slot_no' : '005',
                    'seat_no' : '02',                    
                    'empty' : False
                }, {
                    'slot_no' : '005',
                    'seat_no' : '03',                    
                    'empty' : True
                }, {
                    'slot_no' : '006',
                    'seat_no' : '01',                    
                    'empty' : False
                }, {
                    'slot_no' : '006',
                    'seat_no' : '02',                    
                    'empty' : False
                }, {
                    'slot_no' : '006',
                    'seat_no' : '03',                    
                    'empty' : True
                }
                ]
            },
            {
                '001003': [{
                    'slot_no' : '004',
                    'seat_no' : '01',
                    'empty' : True
                }, {
                    'slot_no' : '004',
                    'seat_no' : '02',
                    'empty' : True
                }, {
                    'slot_no' : '005',
                    'seat_no' : '01',                    
                    'empty' : True
                }, {
                    'slot_no' : '005',
                    'seat_no' : '01',                    
                    'empty' : True
                }, {
                    'slot_no' : '005',
                    'seat_no' : '02',                    
                    'empty' : True
                }, {
                    'slot_no' : '005',
                    'seat_no' : '03',                    
                    'empty' : True
                }, {
                    'slot_no' : '006',
                    'seat_no' : '01',                    
                    'empty' : False
                }, {
                    'slot_no' : '006',
                    'seat_no' : '02',                    
                    'empty' : False
                }, {
                    'slot_no' : '006',
                    'seat_no' : '03',                    
                    'empty' : False
                }
                ]
            }
        ],
        '하행' : [
            {
                '001004': [{
                    'slot_no' : '004',
                    'seat_no' : '01',
                    'empty' : False
                }, {
                    'slot_no' : '004',
                    'seat_no' : '02',                    
                    'empty' : True
                }, {
                    'slot_no' : '004',
                    'seat_no' : '03',                    
                    'empty' : True
                }, {
                    'slot_no' : '005',
                    'seat_no' : '01',                    
                    'empty' : True
                }, {
                    'slot_no' : '005',
                    'seat_no' : '02',                    
                    'empty' : True
                }, {
                    'slot_no' : '005',
                    'seat_no' : '03',                    
                    'empty' : False
                }, {
                    'slot_no' : '006',
                    'seat_no' : '01',                    
                    'empty' : True
                }, {
                    'slot_no' : '006',
                    'seat_no' : '02',                    
                    'empty' : True
                }, {
                    'slot_no' : '006',
                    'seat_no' : '03',                    
                    'empty' : True
                }
                ]
            },
            {
                '001005': [{
                    'slot_no' : '004',
                    'seat_no' : '01',
                    'empty' : False
                }, {
                    'slot_no' : '004',
                    'seat_no' : '02',
                    'empty' : False
                }, {
                    'slot_no' : '004',
                    'seat_no' : '03',                    
                    'empty' : True
                }, {
                    'slot_no' : '005',
                    'seat_no' : '01',                    
                    'empty' : False
                }, {
                    'slot_no' : '005',
                    'seat_no' : '02',                    
                    'empty' : False
                }, {
                    'slot_no' : '005',
                    'seat_no' : '03',                    
                    'empty' : True
                }, {
                    'slot_no' : '006',
                    'seat_no' : '01',                    
                    'empty' : True
                }, {
                    'slot_no' : '006',
                    'seat_no' : '02',                    
                    'empty' : True
                }, {
                    'slot_no' : '006',
                    'seat_no' : '03',                    
                    'empty' : True
                
                }]
            }
        ],

    }
    return JsonResponse(context)

def index(request):
    trains = Train.objects.all()
    # tt = Train.objects.values('train_no').annotate(total=Count('train_no'))
    train_list = list(Train.objects.filter().values('train_no').order_by('train_no').distinct())
    print(type(train_list))
    print(train_list)

    train_no_list = []
    t_list = []
    for train in train_list:
        print(train.get('train_no'))
        train_no = train.get('train_no')
        train_no_list.append(train_no)

        my_train = Train.objects.filter(train_no=train_no)
        t_list.append(list(my_train))


    notifications = Notification.objects.all()

    context = {
        'train_no_list' : train_no_list,
        'tt' : t_list,
        'trains' : trains,
        'notifications': notifications,
    }
    return render(request, 'webserver/index.html', context)

def new(request):

    if request.method == "POST":
        form = TrainForm(request.POST)
        print("뿜뿜")
        if form.is_valid():

            train_no = form.cleaned_data.get('train_no')
            print(train_no)
            slot_no = form.cleaned_data.get('slot_no')
            seat_no = form.cleaned_data.get('seat_no')
            train = Train.objects.create(train_no=train_no, slot_no=slot_no, seat_no=seat_no, empty="False")
        
        return redirect('webserver:index')
    else:
        form = TrainForm()

    context = {
        'form' : form ,
    }

    return render(request, 'webserver/form.html', context)

def train_detail(request, train_no):
    print(train_no)

pinkLightProject/config/templates/webserver/_navbar.html
{% load  static %}
<nav class="mt-1 mb-5 navbar navbar-expand-lg navbar-light" style="background-color: rgb(251, 225, 225); ">
  <a class="navbar-brand" href="#">
    <img style="width:20%; height:20%;" src="{% static 'webserver/image/logo.png' %}" alt="Here_You_Are" >
  </a>
  <button class="navbar-toggler"  type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'webserver:index' %}">홈으로</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'webserver:new' %}">열차추가</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'webserver:index' %}">로그아웃</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a> 관리자 전용 페이지 입니다.  </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'accounts:login' %}">Login</a>
        </li>
      {% endif %}
    </ul>
    <ul class="nav nav-pills">
      <li class="nav-item dropdown">
        <a  class="nav-link dropdown-toggle text-light" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"  style="background-color: rgb(255, 128, 128); ">열차 바로가기</a>
        <div class="dropdown-menu">
        {% for train_no in train_no_list %}
          <a class="dropdown-item" href="{% url 'webserver:train_detail' train_no %}">{{train_no}}번</a>        
        {% endfor %}
        </div>
      </li>
    </ul>
  </div>
</nav>

pinkLightProject/config/templates/webserver/_toast.html
<!-- Flexbox container for aligning the toasts -->
{% load humanize %}
<div class="col-6 col-md-4 mb-3">
  <div aria-live="polite" aria-atomic="true" class="d-flex justify-content-center align-items-center " style="min-height: 200px;">

    <!-- Then put toasts within -->
    <div class="toast rounded border border-dark bg-light" role="alert" aria-live="assertive" aria-atomic="true" autohide: false,>
      <div class="m-3 toast-header ">

          <div style="display:inline; width: 5px; height: 5px" class="bg-success text-success">ㅁ</div>
        {% comment %} {% if pink_light.empty %}
          <div style="display:inline; width: 5px; height: 5px" class="bg-success text-success">ㅁ</div>
        {% else %}
          <div style="display:inline; width: 5px; height: 5px" class="bg-danger text-danger">ㅁ</div>
        {% endif %} {% endcomment %}
  
        <strong class="mr-auto">알림</strong>
        <div style="display:inline; float:right;" >
          <span>{{notification.created_at|naturaltime}}</span>
          <form action="{% url 'webserver:delete_notification' notification.pk %}" method="post" style="display:inline;">
          {% csrf_token %}
            <input type="submit" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close" value="&times;">
              {% comment %} <a href="{% url 'webserver:delete_notification' notification.pk %}" aria-hidden="true">&times;</a> {% endcomment %}
            </button>      
          </form>        
        </div>
      </div>
      <hr>
      <div class="mx-3 mt-3 mb-4 toast-body">
        {{ notification.content }}
      </div>
    </div>
  </div>
</div>

pinkLightProject/config/templates/webserver/_train_no.html
<div class="col-12 col-sm-6 col-md-4 mb-3">
  <div class="card">
    <div class="card-body">
      <h5 style="display : inline;" class="card-title">
        {{ train.train_no }} 번 열차 {{train.slot_no}} 번째 칸 {{train.seat_no}} 번 임산부석
      </h5>
    </div>

    {% if train.empty  %}
      <span class="p-3 mb-2 bg-success text-white">이용가능</span>
    {% else %}
      <span class="p-3 mb-2 bg-danger text-white">이용중</span>
    {% endif %}
  </div>
  <a href="{% url 'webserver:detail' train.pk %}" class="mt-1 mb-4 btn btn-info">상세보기</a>
</div> 

pinkLightProject/config/templates/webserver/_trains.html
<div class="col-12 mb-3">
  <div class="card">
    <div class="card-body">
      <p style="display : inline;" class="card-title">
        {{ train }} 번 열차
      </p>
      {% comment %} <a class="btn btn-secondary" href="#" >&or;</a>  {% endcomment %}
      <a data-toggle="collapse" href="#aa" role="button" aria-expanded="false" aria-controls="aa" style="float : right;" class="btn btn-light" href="#" >&or;</a> 
    </div>
    <div class="collapse" id="aa">
      <div class="card card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
      </div>
    </div>
  </div>
</div> 

pinkLightProject/config/templates/webserver/detail.html
{% extends 'base.html' %}
{% block body %}
  <div class="mt-4 col-7">
    <div class="card">
      <div class="card-body">
        <h5 style="display : inline;" class="card-title">
          {{ train.train_no }} 번 열차 {{train.slot_no}} 번째 칸 {{train.seat_no}} 번 임산부석
        </h5>
      </div>
      {% if train.empty  %}
          <span class="p-3 mb-2 bg-danger text-white">이용중</span>
        {% else %}
          <span class="p-3 mb-2 bg-success text-white">이용가능</span>
        {% endif %}
    </div>
  </div> 
  <div class="container">
    <div class="mt-4 row row justify-content-center">
      <div class="col-12 col-sm-9  col-md-10 mb-3">
        <a href="{% url 'webserver:edit' train.pk %}" class="btn btn-warning">열차 정보 수정하기</a>
        <form action="{% url 'webserver:edit' train.pk %}" method="POST" style="display : inline;" onclick="return confirm('정말로 삭제하시겠습니까')">
          {% csrf_token %}
          <input class="btn btn-danger"  type="submit" value="열차삭제">
        </form>
      </div>
    </div>
  </div>

{% endblock body %}

pinkLightProject/config/templates/webserver/form.html
{% extends 'base.html' %}

{% load bootstrap4 %}


{% block body %}

<form action="" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-warning">
    {% if request.resolver_match.url_name == 'new' %}
          추가하기
    {% else %}
          수정하기  
    {% endif %}
    </button>
  {% endbuttons %}
</form>


{% endblock  %}

pinkLightProject/config/templates/webserver/index.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block notify %}
  <div class="ml-2">
    <p>
      <button class="btn" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" style="background-color: rgb(255, 128, 128)">
        알림
      </button>
    </p>
  </div>
  <div class="collapsing" id="collapseExample">
    {% if notifications %}
      <div class="jumbotron jumbotron-fluid bg-warning" >
        <div class="row m-1">
          {% if user.is_authenticated %}
            {% for notification in notifications %}
              {% include 'webserver/_toast.html' %}
            {% empty %}
            <p> 새로운 알림이 없습니다. </p>
            {% endfor %}    
          {% endif %}

        </div>
      </div>

    {% endif %}
  </div>
{% endblock notify %}


{% block body %}


<div class="container">
  <div class="row mt-4">
    {% if user.is_authenticated %}
      {% for train in train_no_list %}
        {% include 'webserver/_trains.html' %}
      {% empty %}
      <p>열차에 대한 정보가 없습니다.</p>
      {% endfor %}    
    {% else %}
      <p>관리자 전용 </p>
    {% endif %}

  </div>
<div>

<div class="container">
  <div class="row mt-4">
    {% if user.is_authenticated %}
      {% for train in trains %}
        {% include 'webserver/_train_no.html' %}
      {% empty %}
      <p>열차에 대한 정보가 없습니다.</p>
      {% endfor %}    
    {% else %}
      <p>관리자 전용 </p>
    {% endif %}

  </div>

<div>

{% endblock  %}

pinkLightProject/config/templates/webserver/train_detail.html
{% extends 'base.html' %}

{% block body %}

{{trains}}

{% comment %} {% for train in trains  %}
{% if train.empty %}

{% endif %}
{% endfor %} {% endcomment %}


{% endblock body %}