pinkLightProject/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('websockets/', include('websockets.urls')),
    path('webserver/', include('webserver.urls')),
    path('admin/', admin.site.urls),
]

pinkLightProject/websockets/urls.py
from django.urls import path
from . import views

app_name = "websockets"
urlpatterns = [
    path('', views.index, name="index"),
    path('server/', views.server, name="server"),
    path('client/', views.client, name="client"),
]

pinkLightProject/websockets/views.py
from django.shortcuts import render, redirect
from socket import * 

# Create your views here.
def index(request):
    return render(request, 'websockets/index.html')

def client(request):
    clientSocket = socket(AF_INET, SOCK_STREAM)
    clientSocket.connect(('127.0.0.1', 8080))

    print("연결 확인")
    clientSocket.send('나는야 클라이언트', encode('utf-8'))

    print('메시지를 전송했습니다.')

    data = clientSocket.recv(1024)

    print('받은 데이터 : ', data.decode('utf-8'))
    return render(request, 'websockets/index.html')



def server(request):
    print('나는야 서버')
    serverSocket = socket(AF_INET, SOCK_STREAM)
    serverSocket.bind(('', 8080))
    # 클라이언트의 접속 기다렷
    serverSocket.listen(1)

    connectionSock, addr = serverSocket.accept()

    print(str(addr), '에서의 접속 확인')

    data = connectionSock.recv(1024)
    
    print('받은 데이터 : ', data.decode('utf-8'))

    connectionSock.send('I am a server.'.encode('utf-8'))

    print('메시지를 전송했습니다.')
    
    return render(request, 'websockets/index.html')

pinkLightProject/config/templates/websockets/index.html
<html>
  <head></head>
  <body>
    {% comment %} <button id="server-button"> 서버 켜기 </button>
    <button id="client-button"> 클라이언트  </button> {% endcomment %}

    <h1>아아아</h1>

    <form action="{% url 'websockets:server' %} " method="post">
    <label for="text">SERVER</label>
    {% csrf_token %}
      <input type="submit" value="서버 켜기">
    </form> 

    <form action="{% url 'websockets:client' %} " method="post">
    <label for="text">CLIENT</label>
    {% csrf_token %}
      <input type="submit" value="클라이언트 켜기">
    </form> 


    <script>
      const button = document.getElementById('server-button')
      button.addEventListener('click', function(){
        console.log('버튼이 클릭됨')
      })

      const button = document.getElementById('client-button')
      button.addEventListener('click', function(){
        console.log('버튼이 클릭됨')
      })

    </script>

  </body>
</html>